
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(forcats)
```

```{r, echo = F}
BallotImage <- read_tsv("http://www.sfelections.org/results/20161108/data/20161206/20161206_ballotimage.txt", col_names = F) %>%
  separate(X1, c("contest_id",
                 "pref_voter_id",
                 "serial_number",
                 "tally_type_id",
                 "precinct_id",
                 "vote_rank",
                 "candidate_id",
                 "over_vote",
                 "under_vote"),
           sep = c(7,16,23,26,33,36,43,44)) %>%
  mutate(tally_type_id = as.integer(tally_type_id),
         vote_rank = factor(vote_rank,
                            ordered = T,
                            levels = c("001","002","003")),
         vote_rank = fct_recode(vote_rank,
                                "1" = "001",
                                "2" = "002",
                                "3" = "003"),
         over_vote = as.integer(over_vote),
         under_vote = as.integer(under_vote))

MasterLookup <- read_tsv("http://www.sfelections.org/results/20161108/data/20161206/20161206_masterlookup.txt", col_names = F) %>%
  separate(X1, c("record_type",
                 "id",
                 "description",
                 "list_order",
                 "candidates_contest_id",
                 "is_writein",
                 "is_provisional"),
           sep = c(10,17,67,74,81,82)) %>%
  mutate(record_type = trimws(record_type),
         description = trimws(description),
         is_writein = as.integer(is_writein),
         is_provisional = as.integer(is_provisional))

Candidates <- MasterLookup %>%
  filter(record_type == "Candidate") %>%
  select(id, description) %>%
  rename(candidate = description)
Contests <- MasterLookup %>%
  filter(record_type == "Contest") %>%
  select(id, description) %>%
  rename(contest = description)
Precincts <- MasterLookup %>%
  filter(record_type == "Precinct") %>%
  select(id, description) %>%
  rename(precinct = description)
Tallies <- MasterLookup %>%
  filter(record_type == "Tally Type") %>%
  select(id, description) %>%
  mutate(id = as.integer(id)) %>%
  rename(tally = description)

BallotImage <- left_join(BallotImage, Candidates, by = c("candidate_id" = "id"))
BallotImage <- left_join(BallotImage, Contests, by = c("contest_id" = "id"))
BallotImage <- left_join(BallotImage, Precincts, by = c("precinct_id" = "id"))
BallotImage <- left_join(BallotImage, Tallies, by = c("tally_type_id" = "id"))
```

```{r}
UsefulImage <- BallotImage %>%
  select(pref_voter_id, contest, vote_rank, candidate, precinct)
for (i in c(1, 3, 5, 7, 9, 11)) {
  assign(paste0("District", i), 
       UsefulImage %>% 
         filter(contest == paste("Board of Supervisors, District", i, sep = " ")))
}
```

```{r}
round0 <- data.frame(unique(District1$candidate))
colnames(round0) <- c("candidate") 
loser0 <- data.frame(c("johndoe"))
colnames(loser0) <- c("candidate")
a <- (nrow(round0) - 2)
for (i in 0:a) {
  assign(
    paste0("round", i+1), 
      District1 %>%
      filter(!(candidate %in% get(paste0("loser", i))[['candidate']])) %>%
      group_by(pref_voter_id) %>%
      filter(vote_rank == min(vote_rank)) %>% 
      ungroup() %>%
      group_by(candidate) %>%
      summarise(total = n()) %>%
      arrange(desc(total)))
  b <- get(paste0("round", i+1)) %>% filter(!is.na(candidate))
  assign(paste0("round", i+1),
          mutate(
            get(paste0("round", i+1)), 
            prop = total/sum(b$total)))
  assign(
    paste0("loser", i+1), 
      get(paste0("round", i+1)) %>% 
      arrange(total) %>%
      filter(!is.na(candidate)) %>%
      head(n = 1) %>%
      select(candidate) %>%
      rbind(get(paste0("loser", i))))
  assign(
    paste0("round", i+1),
      right_join(get(paste0("round", i+1)),
      get(paste0("round", i)), 
      by = "candidate"))
}
get(paste0("round", a))
```


```{r, eval = F, echo = T}
round1 <- District1 %>%
  group_by(pref_voter_id) %>%
  filter(vote_rank == min(vote_rank)) %>%
  ungroup() %>%
  group_by(candidate) %>%
  summarise(total = n()) %>%
  mutate(prop = total/sum(total)) %>%
  arrange(desc(total))
loser1 <- round1 %>% 
  arrange(total) %>%
  filter(!is.na(candidate)) %>%
  head(n = 1) %>%
  select(candidate)

round2 <- District1 %>%
  filter(!(candidate %in% loser1[['candidate']])) %>%
  group_by(pref_voter_id) %>%
  filter(vote_rank == min(vote_rank)) %>% 
  ungroup() %>%
  group_by(candidate) %>%
  summarise(total = n()) %>%
  mutate(prop = total/sum(total)) %>%
  arrange(desc(total))
loser2 <- round2 %>% 
  arrange(total) %>%
  filter(!is.na(candidate)) %>%
  head(n = 1) %>%
  select(candidate) %>%
  rbind(loser1)
round2 <- right_join(round2, round1, by = "candidate")

v <- c(get(paste0("loser", 2))[['candidate']])
round3 <- District1 %>%
  filter(!(candidate %in% v)) %>%
  group_by(pref_voter_id) %>%
  filter(vote_rank == min(vote_rank)) %>% 
  ungroup() %>%
  group_by(candidate) %>%
  summarise(total = n()) %>%
  mutate(prop = total/sum(total)) %>%
  arrange(desc(total))
loser3 <- round3 %>% 
  arrange(total) %>%
  filter(!is.na(candidate)) %>%
  head(n = 1) %>%
  select(candidate) %>%
  rbind(loser2)
round3 <- right_join(round3, round2, by = "candidate")

i = 3
assign(
  paste0("round", (i+1)), District1 %>%
    filter(!(candidate %in% get(paste0("loser", i))[['candidate']])) %>%
    group_by(pref_voter_id) %>%
    filter(vote_rank == min(vote_rank)) %>% 
    ungroup() %>%
    group_by(candidate) %>%
    summarise(total = n()) %>%
    mutate(proportion = total/sum(total)) %>%
    arrange(desc(total)))
assign(
  paste("loser", (i+1)), get(paste0("round", (i+1))) %>% 
    arrange(total) %>%
    filter(!is.na(candidate)) %>%
    head(n = 1) %>%
    select(candidate) %>%
    rbind(get(paste0("loser", i))))
assign(
  paste0("round", (i+1)), 
    right_join(get(paste0("round", (i+1))),
    get(paste0("round", i)), 
    by = "candidate"))
```

